"""new fields in user model

Revision ID: 60825a4deed3
Revises: dd44673d62be
Create Date: 2018-10-15 22:23:31.082000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60825a4deed3'
down_revision = 'dd44673d62be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('price2', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('price3', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('price4', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('price5', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rank2', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rank3', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rank4', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rank5', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank5')
    op.drop_column('user', 'rank4')
    op.drop_column('user', 'rank3')
    op.drop_column('user', 'rank2')
    op.drop_column('user', 'price5')
    op.drop_column('user', 'price4')
    op.drop_column('user', 'price3')
    op.drop_column('user', 'price2')
    # ### end Alembic commands ###
