"""new fields in user model change

Revision ID: 98bdaa006463
Revises: 60825a4deed3
Create Date: 2018-10-15 22:50:09.898000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98bdaa006463'
down_revision = '60825a4deed3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'price1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'price2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'price3',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'price4',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'price5',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'rank1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'rank2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'rank3',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'rank4',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user', 'rank5',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'rank5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'rank4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'rank3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'rank2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'rank1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'price5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'price4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'price3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'price2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user', 'price1',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
