"""new fields in user model

Revision ID: dd44673d62be
Revises: b9701754d29f
Create Date: 2018-10-15 20:42:36.447000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd44673d62be'
down_revision = 'b9701754d29f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('price1', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rank1', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'rank1')
    op.drop_column('user', 'price1')
    # ### end Alembic commands ###
